//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWebAfip.ar.gov.afip.servicios1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/", ConfigurationName="ar.gov.afip.servicios1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.FERecuperaQTYResponse FERecuperaQTYRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FERecuperaQTYResponse> FERecuperaQTYRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEDummy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.DummyResponse FEDummy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEDummy", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.DummyResponse> FEDummyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.FERecuperaLastCMPResponse FERecuperaLastCMPRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FELastCMPtype argTCMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FERecuperaLastCMPResponse> FERecuperaLastCMPRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FELastCMPtype argTCMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.FEUltNroResponse FEUltNroRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEUltNroResponse> FEUltNroRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEAutRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.FEResponse FEAutRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FERequest Fer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEAutRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEResponse> FEAutRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FERequest Fer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEResponse FEConsultaCAERequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEReq argCAERequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEResponse> FEConsultaCAERequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEReq argCAERequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEAuthRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string signField;
        
        private long cuitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
                this.RaisePropertyChanged("cuit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEConsultaCAEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultadoField;
        
        private vError rErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public vError RError {
            get {
                return this.rErrorField;
            }
            set {
                this.rErrorField = value;
                this.RaisePropertyChanged("RError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class vError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int percodeField;
        
        private string perrmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int percode {
            get {
                return this.percodeField;
            }
            set {
                this.percodeField = value;
                this.RaisePropertyChanged("percode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string perrmsg {
            get {
                return this.perrmsgField;
            }
            set {
                this.perrmsgField = value;
                this.RaisePropertyChanged("perrmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEConsultaCAEReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long cuit_emisorField;
        
        private int tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbt_nroField;
        
        private double imp_totalField;
        
        private string caeField;
        
        private string fecha_cbteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long cuit_emisor {
            get {
                return this.cuit_emisorField;
            }
            set {
                this.cuit_emisorField = value;
                this.RaisePropertyChanged("cuit_emisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
                this.RaisePropertyChanged("tipo_cbte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
                this.RaisePropertyChanged("punto_vta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long cbt_nro {
            get {
                return this.cbt_nroField;
            }
            set {
                this.cbt_nroField = value;
                this.RaisePropertyChanged("cbt_nro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
                this.RaisePropertyChanged("imp_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cae {
            get {
                return this.caeField;
            }
            set {
                this.caeField = value;
                this.RaisePropertyChanged("cae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fecha_cbte {
            get {
                return this.fecha_cbteField;
            }
            set {
                this.fecha_cbteField = value;
                this.RaisePropertyChanged("fecha_cbte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEDetalleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipo_docField;
        
        private long nro_docField;
        
        private int tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbt_desdeField;
        
        private long cbt_hastaField;
        
        private double imp_totalField;
        
        private double imp_tot_concField;
        
        private double imp_netoField;
        
        private double impto_liqField;
        
        private double impto_liq_rniField;
        
        private double imp_op_exField;
        
        private string resultadoField;
        
        private string caeField;
        
        private string fecha_cbteField;
        
        private string fecha_vtoField;
        
        private string motivoField;
        
        private string fecha_serv_desdeField;
        
        private string fecha_serv_hastaField;
        
        private string fecha_venc_pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipo_doc {
            get {
                return this.tipo_docField;
            }
            set {
                this.tipo_docField = value;
                this.RaisePropertyChanged("tipo_doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long nro_doc {
            get {
                return this.nro_docField;
            }
            set {
                this.nro_docField = value;
                this.RaisePropertyChanged("nro_doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
                this.RaisePropertyChanged("tipo_cbte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
                this.RaisePropertyChanged("punto_vta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long cbt_desde {
            get {
                return this.cbt_desdeField;
            }
            set {
                this.cbt_desdeField = value;
                this.RaisePropertyChanged("cbt_desde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long cbt_hasta {
            get {
                return this.cbt_hastaField;
            }
            set {
                this.cbt_hastaField = value;
                this.RaisePropertyChanged("cbt_hasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
                this.RaisePropertyChanged("imp_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double imp_tot_conc {
            get {
                return this.imp_tot_concField;
            }
            set {
                this.imp_tot_concField = value;
                this.RaisePropertyChanged("imp_tot_conc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double imp_neto {
            get {
                return this.imp_netoField;
            }
            set {
                this.imp_netoField = value;
                this.RaisePropertyChanged("imp_neto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double impto_liq {
            get {
                return this.impto_liqField;
            }
            set {
                this.impto_liqField = value;
                this.RaisePropertyChanged("impto_liq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double impto_liq_rni {
            get {
                return this.impto_liq_rniField;
            }
            set {
                this.impto_liq_rniField = value;
                this.RaisePropertyChanged("impto_liq_rni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double imp_op_ex {
            get {
                return this.imp_op_exField;
            }
            set {
                this.imp_op_exField = value;
                this.RaisePropertyChanged("imp_op_ex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string cae {
            get {
                return this.caeField;
            }
            set {
                this.caeField = value;
                this.RaisePropertyChanged("cae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string fecha_cbte {
            get {
                return this.fecha_cbteField;
            }
            set {
                this.fecha_cbteField = value;
                this.RaisePropertyChanged("fecha_cbte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string fecha_vto {
            get {
                return this.fecha_vtoField;
            }
            set {
                this.fecha_vtoField = value;
                this.RaisePropertyChanged("fecha_vto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string fecha_serv_desde {
            get {
                return this.fecha_serv_desdeField;
            }
            set {
                this.fecha_serv_desdeField = value;
                this.RaisePropertyChanged("fecha_serv_desde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string fecha_serv_hasta {
            get {
                return this.fecha_serv_hastaField;
            }
            set {
                this.fecha_serv_hastaField = value;
                this.RaisePropertyChanged("fecha_serv_hasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string fecha_venc_pago {
            get {
                return this.fecha_venc_pagoField;
            }
            set {
                this.fecha_venc_pagoField = value;
                this.RaisePropertyChanged("fecha_venc_pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FECabeceraResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long cuitField;
        
        private string fecha_caeField;
        
        private int cantidadregField;
        
        private string resultadoField;
        
        private string motivoField;
        
        private string reprocesoField;
        
        private int presta_servField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
                this.RaisePropertyChanged("cuit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fecha_cae {
            get {
                return this.fecha_caeField;
            }
            set {
                this.fecha_caeField = value;
                this.RaisePropertyChanged("fecha_cae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int cantidadreg {
            get {
                return this.cantidadregField;
            }
            set {
                this.cantidadregField = value;
                this.RaisePropertyChanged("cantidadreg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string reproceso {
            get {
                return this.reprocesoField;
            }
            set {
                this.reprocesoField = value;
                this.RaisePropertyChanged("reproceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int presta_serv {
            get {
                return this.presta_servField;
            }
            set {
                this.presta_servField = value;
                this.RaisePropertyChanged("presta_serv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FECabeceraResponse fecRespField;
        
        private FEDetalleResponse[] fedRespField;
        
        private vError rErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FECabeceraResponse FecResp {
            get {
                return this.fecRespField;
            }
            set {
                this.fecRespField = value;
                this.RaisePropertyChanged("FecResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public FEDetalleResponse[] FedResp {
            get {
                return this.fedRespField;
            }
            set {
                this.fedRespField = value;
                this.RaisePropertyChanged("FedResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public vError RError {
            get {
                return this.rErrorField;
            }
            set {
                this.rErrorField = value;
                this.RaisePropertyChanged("RError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEDetalleRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipo_docField;
        
        private long nro_docField;
        
        private int tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbt_desdeField;
        
        private long cbt_hastaField;
        
        private double imp_totalField;
        
        private double imp_tot_concField;
        
        private double imp_netoField;
        
        private double impto_liqField;
        
        private double impto_liq_rniField;
        
        private double imp_op_exField;
        
        private string fecha_cbteField;
        
        private string fecha_serv_desdeField;
        
        private string fecha_serv_hastaField;
        
        private string fecha_venc_pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipo_doc {
            get {
                return this.tipo_docField;
            }
            set {
                this.tipo_docField = value;
                this.RaisePropertyChanged("tipo_doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long nro_doc {
            get {
                return this.nro_docField;
            }
            set {
                this.nro_docField = value;
                this.RaisePropertyChanged("nro_doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
                this.RaisePropertyChanged("tipo_cbte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
                this.RaisePropertyChanged("punto_vta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long cbt_desde {
            get {
                return this.cbt_desdeField;
            }
            set {
                this.cbt_desdeField = value;
                this.RaisePropertyChanged("cbt_desde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long cbt_hasta {
            get {
                return this.cbt_hastaField;
            }
            set {
                this.cbt_hastaField = value;
                this.RaisePropertyChanged("cbt_hasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
                this.RaisePropertyChanged("imp_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double imp_tot_conc {
            get {
                return this.imp_tot_concField;
            }
            set {
                this.imp_tot_concField = value;
                this.RaisePropertyChanged("imp_tot_conc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double imp_neto {
            get {
                return this.imp_netoField;
            }
            set {
                this.imp_netoField = value;
                this.RaisePropertyChanged("imp_neto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double impto_liq {
            get {
                return this.impto_liqField;
            }
            set {
                this.impto_liqField = value;
                this.RaisePropertyChanged("impto_liq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double impto_liq_rni {
            get {
                return this.impto_liq_rniField;
            }
            set {
                this.impto_liq_rniField = value;
                this.RaisePropertyChanged("impto_liq_rni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double imp_op_ex {
            get {
                return this.imp_op_exField;
            }
            set {
                this.imp_op_exField = value;
                this.RaisePropertyChanged("imp_op_ex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string fecha_cbte {
            get {
                return this.fecha_cbteField;
            }
            set {
                this.fecha_cbteField = value;
                this.RaisePropertyChanged("fecha_cbte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string fecha_serv_desde {
            get {
                return this.fecha_serv_desdeField;
            }
            set {
                this.fecha_serv_desdeField = value;
                this.RaisePropertyChanged("fecha_serv_desde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string fecha_serv_hasta {
            get {
                return this.fecha_serv_hastaField;
            }
            set {
                this.fecha_serv_hastaField = value;
                this.RaisePropertyChanged("fecha_serv_hasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string fecha_venc_pago {
            get {
                return this.fecha_venc_pagoField;
            }
            set {
                this.fecha_venc_pagoField = value;
                this.RaisePropertyChanged("fecha_venc_pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FECabeceraRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private int cantidadregField;
        
        private int presta_servField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int cantidadreg {
            get {
                return this.cantidadregField;
            }
            set {
                this.cantidadregField = value;
                this.RaisePropertyChanged("cantidadreg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int presta_serv {
            get {
                return this.presta_servField;
            }
            set {
                this.presta_servField = value;
                this.RaisePropertyChanged("presta_serv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FERequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FECabeceraRequest fecrField;
        
        private FEDetalleRequest[] fedrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FECabeceraRequest Fecr {
            get {
                return this.fecrField;
            }
            set {
                this.fecrField = value;
                this.RaisePropertyChanged("Fecr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public FEDetalleRequest[] Fedr {
            get {
                return this.fedrField;
            }
            set {
                this.fedrField = value;
                this.RaisePropertyChanged("Fedr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class UltNroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FEUltNroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UltNroResponse nroField;
        
        private vError rErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UltNroResponse nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
                this.RaisePropertyChanged("nro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public vError RError {
            get {
                return this.rErrorField;
            }
            set {
                this.rErrorField = value;
                this.RaisePropertyChanged("RError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FERecuperaLastCMPResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cbte_nroField;
        
        private vError rErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cbte_nro {
            get {
                return this.cbte_nroField;
            }
            set {
                this.cbte_nroField = value;
                this.RaisePropertyChanged("cbte_nro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public vError RError {
            get {
                return this.rErrorField;
            }
            set {
                this.rErrorField = value;
                this.RaisePropertyChanged("RError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FELastCMPtype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ptoVtaField;
        
        private int tipoCbteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PtoVta {
            get {
                return this.ptoVtaField;
            }
            set {
                this.ptoVtaField = value;
                this.RaisePropertyChanged("PtoVta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TipoCbte {
            get {
                return this.tipoCbteField;
            }
            set {
                this.tipoCbteField = value;
                this.RaisePropertyChanged("TipoCbte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class DummyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appserverField;
        
        private string dbserverField;
        
        private string authserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                this.appserverField = value;
                this.RaisePropertyChanged("appserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                this.dbserverField = value;
                this.RaisePropertyChanged("dbserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                this.authserverField = value;
                this.RaisePropertyChanged("authserver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FERecuperaQTY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
    public partial class FERecuperaQTYResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FERecuperaQTY qtyField;
        
        private vError rErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FERecuperaQTY qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public vError RError {
            get {
                return this.rErrorField;
            }
            set {
                this.rErrorField = value;
                this.RaisePropertyChanged("RError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CSWebAfip.ar.gov.afip.servicios1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CSWebAfip.ar.gov.afip.servicios1.ServiceSoap>, CSWebAfip.ar.gov.afip.servicios1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.FERecuperaQTYResponse FERecuperaQTYRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth) {
            return base.Channel.FERecuperaQTYRequest(argAuth);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FERecuperaQTYResponse> FERecuperaQTYRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth) {
            return base.Channel.FERecuperaQTYRequestAsync(argAuth);
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.DummyResponse FEDummy() {
            return base.Channel.FEDummy();
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.DummyResponse> FEDummyAsync() {
            return base.Channel.FEDummyAsync();
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.FERecuperaLastCMPResponse FERecuperaLastCMPRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FELastCMPtype argTCMP) {
            return base.Channel.FERecuperaLastCMPRequest(argAuth, argTCMP);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FERecuperaLastCMPResponse> FERecuperaLastCMPRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FELastCMPtype argTCMP) {
            return base.Channel.FERecuperaLastCMPRequestAsync(argAuth, argTCMP);
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.FEUltNroResponse FEUltNroRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth) {
            return base.Channel.FEUltNroRequest(argAuth);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEUltNroResponse> FEUltNroRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth) {
            return base.Channel.FEUltNroRequestAsync(argAuth);
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.FEResponse FEAutRequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FERequest Fer) {
            return base.Channel.FEAutRequest(argAuth, Fer);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEResponse> FEAutRequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FERequest Fer) {
            return base.Channel.FEAutRequestAsync(argAuth, Fer);
        }
        
        public CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEResponse FEConsultaCAERequest(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEReq argCAERequest) {
            return base.Channel.FEConsultaCAERequest(argAuth, argCAERequest);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEResponse> FEConsultaCAERequestAsync(CSWebAfip.ar.gov.afip.servicios1.FEAuthRequest argAuth, CSWebAfip.ar.gov.afip.servicios1.FEConsultaCAEReq argCAERequest) {
            return base.Channel.FEConsultaCAERequestAsync(argAuth, argCAERequest);
        }
    }
}
