//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWebAfip.VEConsumerService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class VentanillaWSFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int faultCodeField;
        
        private string faultMessageField;
        
        private string categoryField;
        
        private string[] possibleSolutionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("possibleSolutions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] possibleSolutions {
            get {
                return this.possibleSolutionsField;
            }
            set {
                this.possibleSolutionsField = value;
                this.RaisePropertyChanged("possibleSolutions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws")]
    public partial class adjunto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string filenameField;
        
        private byte[] contentField;
        
        private bool compressedField;
        
        private bool compressedFieldSpecified;
        
        private bool signedField;
        
        private bool signedFieldSpecified;
        
        private bool encryptedField;
        
        private bool encryptedFieldSpecified;
        
        private bool processedField;
        
        private bool processedFieldSpecified;
        
        private bool publicField;
        
        private bool publicFieldSpecified;
        
        private string md5Field;
        
        private long contentSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool compressed {
            get {
                return this.compressedField;
            }
            set {
                this.compressedField = value;
                this.RaisePropertyChanged("compressed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressedSpecified {
            get {
                return this.compressedFieldSpecified;
            }
            set {
                this.compressedFieldSpecified = value;
                this.RaisePropertyChanged("compressedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool signed {
            get {
                return this.signedField;
            }
            set {
                this.signedField = value;
                this.RaisePropertyChanged("signed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signedSpecified {
            get {
                return this.signedFieldSpecified;
            }
            set {
                this.signedFieldSpecified = value;
                this.RaisePropertyChanged("signedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool encrypted {
            get {
                return this.encryptedField;
            }
            set {
                this.encryptedField = value;
                this.RaisePropertyChanged("encrypted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encryptedSpecified {
            get {
                return this.encryptedFieldSpecified;
            }
            set {
                this.encryptedFieldSpecified = value;
                this.RaisePropertyChanged("encryptedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
                this.RaisePropertyChanged("processed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processedSpecified {
            get {
                return this.processedFieldSpecified;
            }
            set {
                this.processedFieldSpecified = value;
                this.RaisePropertyChanged("processedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool @public {
            get {
                return this.publicField;
            }
            set {
                this.publicField = value;
                this.RaisePropertyChanged("public");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicSpecified {
            get {
                return this.publicFieldSpecified;
            }
            set {
                this.publicFieldSpecified = value;
                this.RaisePropertyChanged("publicSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string md5 {
            get {
                return this.md5Field;
            }
            set {
                this.md5Field = value;
                this.RaisePropertyChanged("md5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long contentSize {
            get {
                return this.contentSizeField;
            }
            set {
                this.contentSizeField = value;
                this.RaisePropertyChanged("contentSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Comunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class ComunicacionSimplificada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idComunicacionField;
        
        private long cuitDestinatarioField;
        
        private string fechaPublicacionField;
        
        private string fechaVencimientoField;
        
        private long sistemaPublicadorField;
        
        private string sistemaPublicadorDescField;
        
        private int estadoField;
        
        private string estadoDescField;
        
        private string asuntoField;
        
        private int prioridadField;
        
        private bool tieneAdjuntoField;
        
        private string referencia1Field;
        
        private string referencia2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idComunicacion {
            get {
                return this.idComunicacionField;
            }
            set {
                this.idComunicacionField = value;
                this.RaisePropertyChanged("idComunicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long cuitDestinatario {
            get {
                return this.cuitDestinatarioField;
            }
            set {
                this.cuitDestinatarioField = value;
                this.RaisePropertyChanged("cuitDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("fechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long sistemaPublicador {
            get {
                return this.sistemaPublicadorField;
            }
            set {
                this.sistemaPublicadorField = value;
                this.RaisePropertyChanged("sistemaPublicador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sistemaPublicadorDesc {
            get {
                return this.sistemaPublicadorDescField;
            }
            set {
                this.sistemaPublicadorDescField = value;
                this.RaisePropertyChanged("sistemaPublicadorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string estadoDesc {
            get {
                return this.estadoDescField;
            }
            set {
                this.estadoDescField = value;
                this.RaisePropertyChanged("estadoDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string asunto {
            get {
                return this.asuntoField;
            }
            set {
                this.asuntoField = value;
                this.RaisePropertyChanged("asunto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("prioridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool tieneAdjunto {
            get {
                return this.tieneAdjuntoField;
            }
            set {
                this.tieneAdjuntoField = value;
                this.RaisePropertyChanged("tieneAdjunto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                this.referencia1Field = value;
                this.RaisePropertyChanged("referencia1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                this.referencia2Field = value;
                this.RaisePropertyChanged("referencia2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Comunicacion : ComunicacionSimplificada {
        
        private string mensajeField;
        
        private int tiempoDeVidaField;
        
        private adjunto[] adjuntosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tiempoDeVida {
            get {
                return this.tiempoDeVidaField;
            }
            set {
                this.tiempoDeVidaField = value;
                this.RaisePropertyChanged("tiempoDeVida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public adjunto[] adjuntos {
            get {
                return this.adjuntosField;
            }
            set {
                this.adjuntosField = value;
                this.RaisePropertyChanged("adjuntos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class RespuestaPaginada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int paginaField;
        
        private int totalPaginasField;
        
        private int itemsPorPaginaField;
        
        private int totalItemsField;
        
        private ComunicacionSimplificada[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int totalPaginas {
            get {
                return this.totalPaginasField;
            }
            set {
                this.totalPaginasField = value;
                this.RaisePropertyChanged("totalPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int itemsPorPagina {
            get {
                return this.itemsPorPaginaField;
            }
            set {
                this.itemsPorPaginaField = value;
                this.RaisePropertyChanged("itemsPorPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int totalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
                this.RaisePropertyChanged("totalItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ComunicacionSimplificada[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> estadoField;
        
        private bool estadoFieldSpecified;
        
        private string fechaDesdeField;
        
        private string fechaHastaField;
        
        private System.Nullable<long> comunicacionIdDesdeField;
        
        private bool comunicacionIdDesdeFieldSpecified;
        
        private System.Nullable<long> comunicacionIdHastaField;
        
        private bool comunicacionIdHastaFieldSpecified;
        
        private System.Nullable<bool> tieneAdjuntoField;
        
        private bool tieneAdjuntoFieldSpecified;
        
        private System.Nullable<long> sistemaPublicadorIdField;
        
        private bool sistemaPublicadorIdFieldSpecified;
        
        private int paginaField;
        
        private System.Nullable<int> resultadosPorPaginaField;
        
        private bool resultadosPorPaginaFieldSpecified;
        
        private string referencia1Field;
        
        private string referencia2Field;
        
        public Filter() {
            this.paginaField = 1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fechaDesde {
            get {
                return this.fechaDesdeField;
            }
            set {
                this.fechaDesdeField = value;
                this.RaisePropertyChanged("fechaDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string fechaHasta {
            get {
                return this.fechaHastaField;
            }
            set {
                this.fechaHastaField = value;
                this.RaisePropertyChanged("fechaHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<long> comunicacionIdDesde {
            get {
                return this.comunicacionIdDesdeField;
            }
            set {
                this.comunicacionIdDesdeField = value;
                this.RaisePropertyChanged("comunicacionIdDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comunicacionIdDesdeSpecified {
            get {
                return this.comunicacionIdDesdeFieldSpecified;
            }
            set {
                this.comunicacionIdDesdeFieldSpecified = value;
                this.RaisePropertyChanged("comunicacionIdDesdeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<long> comunicacionIdHasta {
            get {
                return this.comunicacionIdHastaField;
            }
            set {
                this.comunicacionIdHastaField = value;
                this.RaisePropertyChanged("comunicacionIdHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comunicacionIdHastaSpecified {
            get {
                return this.comunicacionIdHastaFieldSpecified;
            }
            set {
                this.comunicacionIdHastaFieldSpecified = value;
                this.RaisePropertyChanged("comunicacionIdHastaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<bool> tieneAdjunto {
            get {
                return this.tieneAdjuntoField;
            }
            set {
                this.tieneAdjuntoField = value;
                this.RaisePropertyChanged("tieneAdjunto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tieneAdjuntoSpecified {
            get {
                return this.tieneAdjuntoFieldSpecified;
            }
            set {
                this.tieneAdjuntoFieldSpecified = value;
                this.RaisePropertyChanged("tieneAdjuntoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<long> sistemaPublicadorId {
            get {
                return this.sistemaPublicadorIdField;
            }
            set {
                this.sistemaPublicadorIdField = value;
                this.RaisePropertyChanged("sistemaPublicadorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sistemaPublicadorIdSpecified {
            get {
                return this.sistemaPublicadorIdFieldSpecified;
            }
            set {
                this.sistemaPublicadorIdFieldSpecified = value;
                this.RaisePropertyChanged("sistemaPublicadorIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> resultadosPorPagina {
            get {
                return this.resultadosPorPaginaField;
            }
            set {
                this.resultadosPorPaginaField = value;
                this.RaisePropertyChanged("resultadosPorPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultadosPorPaginaSpecified {
            get {
                return this.resultadosPorPaginaFieldSpecified;
            }
            set {
                this.resultadosPorPaginaFieldSpecified = value;
                this.RaisePropertyChanged("resultadosPorPaginaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                this.referencia1Field = value;
                this.RaisePropertyChanged("referencia1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                this.referencia2Field = value;
                this.RaisePropertyChanged("referencia2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://core.tecno.afip.gov.ar/model/ws/types")]
    public partial class AuthRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string signField;
        
        private long cuitRepresentadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long cuitRepresentada {
            get {
                return this.cuitRepresentadaField;
            }
            set {
                this.cuitRepresentadaField = value;
                this.RaisePropertyChanged("cuitRepresentada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", ConfigurationName="VEConsumerService.VEConsumer")]
    public interface VEConsumer {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ve.tecno.afip.gov.ar/domain/service/ws/types) of message consultarComunicaciones does not match the default value (http://ve.tecno.afip.gov.ar/domain/service/ws)
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicaciones", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicacionesR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CSWebAfip.VEConsumerService.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.VEConsumerService.consultarComunicacionesResponse consultarComunicaciones(CSWebAfip.VEConsumerService.consultarComunicaciones request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicaciones", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarComunicacionesR" +
            "esponse")]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarComunicacionesResponse> consultarComunicacionesAsync(CSWebAfip.VEConsumerService.consultarComunicaciones request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ve.tecno.afip.gov.ar/domain/service/ws/types) of message consultarSistemasPublicadores does not match the default value (http://ve.tecno.afip.gov.ar/domain/service/ws)
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "dores", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "doresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CSWebAfip.VEConsumerService.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse consultarSistemasPublicadores(CSWebAfip.VEConsumerService.consultarSistemasPublicadores request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "dores", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarSistemasPublica" +
            "doresResponse")]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse> consultarSistemasPublicadoresAsync(CSWebAfip.VEConsumerService.consultarSistemasPublicadores request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummy", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DummyResult")]
        CSWebAfip.VEConsumerService.DummyResult dummy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummy", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/dummyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DummyResult")]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.DummyResult> dummyAsync();
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ve.tecno.afip.gov.ar/domain/service/ws/types) of message consumirComunicacion does not match the default value (http://ve.tecno.afip.gov.ar/domain/service/ws)
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacion", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacionResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CSWebAfip.VEConsumerService.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.VEConsumerService.consumirComunicacionResponse consumirComunicacion(CSWebAfip.VEConsumerService.consumirComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacion", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consumirComunicacionResp" +
            "onse")]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consumirComunicacionResponse> consumirComunicacionAsync(CSWebAfip.VEConsumerService.consumirComunicacion request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ve.tecno.afip.gov.ar/domain/service/ws/types) of message consultarEstados does not match the default value (http://ve.tecno.afip.gov.ar/domain/service/ws)
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstados", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstadosResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CSWebAfip.VEConsumerService.VentanillaWSFault), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="VentanillaWSFault", Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSWebAfip.VEConsumerService.consultarEstadosResponse consultarEstados(CSWebAfip.VEConsumerService.consultarEstados request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstados", ReplyAction="http://ve.tecno.afip.gov.ar/domain/service/ws/VEConsumer/consultarEstadosResponse" +
            "")]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarEstadosResponse> consultarEstadosAsync(CSWebAfip.VEConsumerService.consultarEstados request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarComunicaciones", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    public partial class consultarComunicaciones {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSWebAfip.VEConsumerService.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSWebAfip.VEConsumerService.Filter filter;
        
        public consultarComunicaciones() {
        }
        
        public consultarComunicaciones(CSWebAfip.VEConsumerService.AuthRequest authRequest, CSWebAfip.VEConsumerService.Filter filter) {
            this.authRequest = authRequest;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarComunicacionesResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    public partial class consultarComunicacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        public CSWebAfip.VEConsumerService.RespuestaPaginada RespuestaPaginada;
        
        public consultarComunicacionesResponse() {
        }
        
        public consultarComunicacionesResponse(CSWebAfip.VEConsumerService.RespuestaPaginada RespuestaPaginada) {
            this.RespuestaPaginada = RespuestaPaginada;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Sistema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string descripcionField;
        
        private string certCNsField;
        
        private Subservicio[] subserviciosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certCNs {
            get {
                return this.certCNsField;
            }
            set {
                this.certCNsField = value;
                this.RaisePropertyChanged("certCNs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Subservicio[] subservicios {
            get {
                return this.subserviciosField;
            }
            set {
                this.subserviciosField = value;
                this.RaisePropertyChanged("subservicios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Subservicio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSistemasPublicadores", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    public partial class consultarSistemasPublicadores {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSWebAfip.VEConsumerService.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idSistemaPublicador;
        
        public consultarSistemasPublicadores() {
        }
        
        public consultarSistemasPublicadores(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idSistemaPublicador) {
            this.authRequest = authRequest;
            this.idSistemaPublicador = idSistemaPublicador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSistemasPublicadoresResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    public partial class consultarSistemasPublicadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsNullable=false)]
        public CSWebAfip.VEConsumerService.Sistema[] Sistemas;
        
        public consultarSistemasPublicadoresResponse() {
        }
        
        public consultarSistemasPublicadoresResponse(CSWebAfip.VEConsumerService.Sistema[] Sistemas) {
            this.Sistemas = Sistemas;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class DummyResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dbserverField;
        
        private string appserverField;
        
        private string authserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                this.dbserverField = value;
                this.RaisePropertyChanged("dbserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                this.appserverField = value;
                this.RaisePropertyChanged("appserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                this.authserverField = value;
                this.RaisePropertyChanged("authserver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consumirComunicacion", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    public partial class consumirComunicacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSWebAfip.VEConsumerService.AuthRequest authRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idComunicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool incluirAdjuntos;
        
        public consumirComunicacion() {
        }
        
        public consumirComunicacion(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idComunicacion, bool incluirAdjuntos) {
            this.authRequest = authRequest;
            this.idComunicacion = idComunicacion;
            this.incluirAdjuntos = incluirAdjuntos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consumirComunicacionResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    public partial class consumirComunicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        public CSWebAfip.VEConsumerService.Comunicacion Comunicacion;
        
        public consumirComunicacionResponse() {
        }
        
        public consumirComunicacionResponse(CSWebAfip.VEConsumerService.Comunicacion Comunicacion) {
            this.Comunicacion = Comunicacion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstados", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsWrapped=true)]
    public partial class consultarEstados {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSWebAfip.VEConsumerService.AuthRequest authRequest;
        
        public consultarEstados() {
        }
        
        public consultarEstados(CSWebAfip.VEConsumerService.AuthRequest authRequest) {
            this.authRequest = authRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstadosResponse", WrapperNamespace="http://ve.tecno.afip.gov.ar/domain/service/ws", IsWrapped=true)]
    public partial class consultarEstadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ve.tecno.afip.gov.ar/domain/service/ws/types", IsNullable=false)]
        public CSWebAfip.VEConsumerService.Estado[] Estados;
        
        public consultarEstadosResponse() {
        }
        
        public consultarEstadosResponse(CSWebAfip.VEConsumerService.Estado[] Estados) {
            this.Estados = Estados;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VEConsumerChannel : CSWebAfip.VEConsumerService.VEConsumer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VEConsumerClient : System.ServiceModel.ClientBase<CSWebAfip.VEConsumerService.VEConsumer>, CSWebAfip.VEConsumerService.VEConsumer {
        
        public VEConsumerClient() {
        }
        
        public VEConsumerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VEConsumerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VEConsumerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VEConsumerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSWebAfip.VEConsumerService.consultarComunicacionesResponse CSWebAfip.VEConsumerService.VEConsumer.consultarComunicaciones(CSWebAfip.VEConsumerService.consultarComunicaciones request) {
            return base.Channel.consultarComunicaciones(request);
        }
        
        public CSWebAfip.VEConsumerService.RespuestaPaginada consultarComunicaciones(CSWebAfip.VEConsumerService.AuthRequest authRequest, CSWebAfip.VEConsumerService.Filter filter) {
            CSWebAfip.VEConsumerService.consultarComunicaciones inValue = new CSWebAfip.VEConsumerService.consultarComunicaciones();
            inValue.authRequest = authRequest;
            inValue.filter = filter;
            CSWebAfip.VEConsumerService.consultarComunicacionesResponse retVal = ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarComunicaciones(inValue);
            return retVal.RespuestaPaginada;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarComunicacionesResponse> CSWebAfip.VEConsumerService.VEConsumer.consultarComunicacionesAsync(CSWebAfip.VEConsumerService.consultarComunicaciones request) {
            return base.Channel.consultarComunicacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarComunicacionesResponse> consultarComunicacionesAsync(CSWebAfip.VEConsumerService.AuthRequest authRequest, CSWebAfip.VEConsumerService.Filter filter) {
            CSWebAfip.VEConsumerService.consultarComunicaciones inValue = new CSWebAfip.VEConsumerService.consultarComunicaciones();
            inValue.authRequest = authRequest;
            inValue.filter = filter;
            return ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarComunicacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse CSWebAfip.VEConsumerService.VEConsumer.consultarSistemasPublicadores(CSWebAfip.VEConsumerService.consultarSistemasPublicadores request) {
            return base.Channel.consultarSistemasPublicadores(request);
        }
        
        public CSWebAfip.VEConsumerService.Sistema[] consultarSistemasPublicadores(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idSistemaPublicador) {
            CSWebAfip.VEConsumerService.consultarSistemasPublicadores inValue = new CSWebAfip.VEConsumerService.consultarSistemasPublicadores();
            inValue.authRequest = authRequest;
            inValue.idSistemaPublicador = idSistemaPublicador;
            CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse retVal = ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarSistemasPublicadores(inValue);
            return retVal.Sistemas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse> CSWebAfip.VEConsumerService.VEConsumer.consultarSistemasPublicadoresAsync(CSWebAfip.VEConsumerService.consultarSistemasPublicadores request) {
            return base.Channel.consultarSistemasPublicadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarSistemasPublicadoresResponse> consultarSistemasPublicadoresAsync(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idSistemaPublicador) {
            CSWebAfip.VEConsumerService.consultarSistemasPublicadores inValue = new CSWebAfip.VEConsumerService.consultarSistemasPublicadores();
            inValue.authRequest = authRequest;
            inValue.idSistemaPublicador = idSistemaPublicador;
            return ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarSistemasPublicadoresAsync(inValue);
        }
        
        public CSWebAfip.VEConsumerService.DummyResult dummy() {
            return base.Channel.dummy();
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.DummyResult> dummyAsync() {
            return base.Channel.dummyAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSWebAfip.VEConsumerService.consumirComunicacionResponse CSWebAfip.VEConsumerService.VEConsumer.consumirComunicacion(CSWebAfip.VEConsumerService.consumirComunicacion request) {
            return base.Channel.consumirComunicacion(request);
        }
        
        public CSWebAfip.VEConsumerService.Comunicacion consumirComunicacion(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idComunicacion, bool incluirAdjuntos) {
            CSWebAfip.VEConsumerService.consumirComunicacion inValue = new CSWebAfip.VEConsumerService.consumirComunicacion();
            inValue.authRequest = authRequest;
            inValue.idComunicacion = idComunicacion;
            inValue.incluirAdjuntos = incluirAdjuntos;
            CSWebAfip.VEConsumerService.consumirComunicacionResponse retVal = ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consumirComunicacion(inValue);
            return retVal.Comunicacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consumirComunicacionResponse> CSWebAfip.VEConsumerService.VEConsumer.consumirComunicacionAsync(CSWebAfip.VEConsumerService.consumirComunicacion request) {
            return base.Channel.consumirComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consumirComunicacionResponse> consumirComunicacionAsync(CSWebAfip.VEConsumerService.AuthRequest authRequest, long idComunicacion, bool incluirAdjuntos) {
            CSWebAfip.VEConsumerService.consumirComunicacion inValue = new CSWebAfip.VEConsumerService.consumirComunicacion();
            inValue.authRequest = authRequest;
            inValue.idComunicacion = idComunicacion;
            inValue.incluirAdjuntos = incluirAdjuntos;
            return ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consumirComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSWebAfip.VEConsumerService.consultarEstadosResponse CSWebAfip.VEConsumerService.VEConsumer.consultarEstados(CSWebAfip.VEConsumerService.consultarEstados request) {
            return base.Channel.consultarEstados(request);
        }
        
        public CSWebAfip.VEConsumerService.Estado[] consultarEstados(CSWebAfip.VEConsumerService.AuthRequest authRequest) {
            CSWebAfip.VEConsumerService.consultarEstados inValue = new CSWebAfip.VEConsumerService.consultarEstados();
            inValue.authRequest = authRequest;
            CSWebAfip.VEConsumerService.consultarEstadosResponse retVal = ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarEstados(inValue);
            return retVal.Estados;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarEstadosResponse> CSWebAfip.VEConsumerService.VEConsumer.consultarEstadosAsync(CSWebAfip.VEConsumerService.consultarEstados request) {
            return base.Channel.consultarEstadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSWebAfip.VEConsumerService.consultarEstadosResponse> consultarEstadosAsync(CSWebAfip.VEConsumerService.AuthRequest authRequest) {
            CSWebAfip.VEConsumerService.consultarEstados inValue = new CSWebAfip.VEConsumerService.consultarEstados();
            inValue.authRequest = authRequest;
            return ((CSWebAfip.VEConsumerService.VEConsumer)(this)).consultarEstadosAsync(inValue);
        }
    }
}
